# Generated by Django 3.2 on 2023-01-05 07:39

import authentication.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_organization_algorithm_organization_cash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=authentication.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'gif'])]),
        ),
    ]
