# Generated by Django 3.2 on 2023-01-05 09:08

import authentication.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20230105_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=authentication.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'gif', 'jpg'])]),
        ),
    ]
