# Generated by Django 3.2 on 2023-01-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='notification_interval',
            field=models.IntegerField(default=1800),
        ),
    ]
