# Generated by Django 3.2 on 2024-03-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_organization_notification_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('organization', 'phone')},
        ),
    ]
