# Generated by Django 3.2 on 2023-01-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationmanager_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmanager',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
