apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx-depl
  namespace: angizeh-2
  annotations: {}
  creationTimestamp: null
  generation: 1
  labels:
    app: influxdb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: influxdb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: influxdb
    spec:
      containers:
      - env:
           - name: DOCKER_INFLUXDB_INIT_MODE
             value: setup
           - name: DOCKER_INFLUXDB_INIT_USERNAME
             value: leo
           - name: DOCKER_INFLUXDB_INIT_PASSWORD
             value: Goldenhand76
           - name: DOCKER_INFLUXDB_INIT_ORG
             value: angizeh
           - name: DOCKER_INFLUXDB_INIT_BUCKET
             value: IoT
           - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
             value: mytoken
        image: influxdb:2.3.0-alpine
        imagePullPolicy: Always
        name: influxdb
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: var-lib-influxdb
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: var-lib-influxdb
        persistentVolumeClaim:
          claimName: influx-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-claim
  namespace: angizeh-2
  labels:
    app: influxdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: influx-clusterip-srv
  namespace: angizeh-2
  labels:
    app: influxdb
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
    - name: influxdb
      protocol: TCP
      port: 8086
      targetPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: influx-loadbalancer
  namespace: angizeh-2
spec:
  type: LoadBalancer
  selector:
    app: influxdb
  ports:
  - protocol: TCP
    port: 8086
    targetPort: 8086