apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-claim
  namespace: angizeh-2
  labels:
    app: postgres
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany