# Generated by Django 4.0.1 on 2022-09-26 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('ONCE', 'ONCE'), ('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('SEASONALLY', 'Seasonally'), ('YEARLY', 'Yearly')], max_length=16)),
                ('set_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Continues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('LT', 'Lower Than'), ('HT', 'Higher Than'), ('EQ', 'Equal To')], max_length=2)),
                ('set_point', models.FloatField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Binary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('SWITCH', 'SWITCH')], max_length=6)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.sensor')),
            ],
        ),
    ]
