# Generated by Django 3.2 on 2023-01-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='update_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
