# Generated by Django 4.0.1 on 2022-09-26 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '__first__'),
        ('authentication', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('title', models.CharField(default='', max_length=64, unique=True)),
                ('path', models.FilePathField(blank=True, null=True, path='/var/www/Angizeh_2/Smart_Plans/', unique=True)),
                ('active', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.organization')),
            ],
            options={
                'db_table': 'smart_tile',
            },
        ),
        migrations.CreateModel(
            name='ManualTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('title', models.CharField(default='', max_length=24)),
                ('order', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=False)),
                ('lock', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('WAITING', 'WAITING'), ('STARTED', 'STARTED'), ('RETRYING', 'RETRYING'), ('SUCCEED', 'SUCCEED'), ('FAILED', 'FAILED')], default='WAITING', max_length=8)),
                ('actuator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.actuator')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.organization')),
            ],
            options={
                'db_table': 'manual_tile',
                'ordering': ('field', 'order'),
            },
        ),
        migrations.CreateModel(
            name='AutomaticTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('type', models.CharField(choices=[('regulation', 'regulation'), ('schedule', 'schedule')], max_length=16)),
                ('title', models.CharField(max_length=24, unique=True)),
                ('condition_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('delay_status', models.BooleanField(default=False)),
                ('delay', models.CharField(blank=True, max_length=3, null=True)),
                ('output', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('SWITCH', 'SWITCH')], default='ON', max_length=8)),
                ('order', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=False)),
                ('lock', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('WAITING', 'WAITING'), ('STARTED', 'STARTED'), ('RETRYING', 'RETRYING'), ('SUCCEED', 'SUCCEED'), ('FAILED', 'FAILED')], default='WAITING', max_length=8)),
                ('actuator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.actuator')),
                ('condition_content_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ('continues', 'binary', 'schedule')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.organization')),
            ],
            options={
                'db_table': 'automatic_tile',
                'ordering': ('field', 'order'),
            },
        ),
        migrations.AddConstraint(
            model_name='manualtile',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('title', 'actuator'), name='unique_manual_name'),
        ),
    ]
