# Generated by Django 4.0.1 on 2022-09-29 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualtile',
            name='actuator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.actuator', unique=True),
        ),
        migrations.AlterField(
            model_name='manualtile',
            name='title',
            field=models.CharField(default='', max_length=24, unique=True),
        ),
    ]
