# Generated by Django 3.2 on 2023-01-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_automatictile_actuator_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualtile',
            name='title',
            field=models.CharField(default='', max_length=24),
        ),
    ]
