# Generated by Django 4.0.1 on 2022-09-26 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24)),
                ('is_favorite', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.organization')),
            ],
            options={
                'db_table': 'tab',
                'ordering': ('field', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24)),
                ('size', models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], max_length=8)),
                ('type', models.CharField(choices=[('Graph', 'Graph'), ('Gauge', 'Gauge')], max_length=8)),
                ('unit', models.CharField(max_length=8)),
                ('precision', models.CharField(choices=[('1', '1'), ('0.1', '0.1')], max_length=8)),
                ('timeRange', models.CharField(blank=True, choices=[('5m', '5m'), ('30m', '30m'), ('1h', '1h'), ('6h', '6h'), ('1d', '1d')], max_length=8, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.sensor')),
                ('sensor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.type')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.tab')),
            ],
            options={
                'db_table': 'tile',
            },
        ),
    ]
