# Generated by Django 4.0.1 on 2022-10-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='status',
            field=models.JSONField(null=True),
        ),
    ]
