# Generated by Django 4.0.1 on 2022-12-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_tile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tile',
            name='interval',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
