# Generated by Django 3.2 on 2024-03-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_tab_location_tile_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='title',
            field=models.CharField(error_messages={'max_length': 'طول فیلد حداکثر 24 کارکتر باشد'}, max_length=24),
        ),
    ]
