# Generated by Django 4.0.1 on 2022-10-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_actuator_automatic_selected_actuator_manual_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='previous_value',
            field=models.FloatField(blank=True, choices=[(0.0, 'off'), (1.0, 'on')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='set_value',
            field=models.FloatField(blank=True, choices=[(0.0, 'off'), (1.0, 'on')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='value',
            field=models.FloatField(blank=True, choices=[(0.0, 'off'), (1.0, 'on')], null=True),
        ),
    ]
