# Generated by Django 3.2 on 2023-01-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_organization_notification_interval'),
        ('device', '0006_auto_20230116_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='title',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='actuator',
            unique_together={('organization', 'title')},
        ),
    ]
