# Generated by Django 3.2 on 2023-02-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_auto_20230129_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
